{
    "vendedores":
    [
        {
            "id":1,
            "eventos":
                [
                    {
                        "mes":1,
                        "dia":10,
                        "hora":7,
                        "desc":"reunion"
                    },
                    {
                        "mes":5,
                        "dia":15,
                        "hora":13,
                        "desc":"Almuerzo"
                    },
                    {
                        "mes":8,
                        "dia":5,
                        "hora":10,
                        "desc":"Almuerzo"
                    },
                    {
                        "mes":9,
                        "dia":15,
                        "hora":12,
                        "desc":"Boda"
                    }

                ]
        },
        {
            "id":2,
            "eventos":
                [
                    {
                        "mes":3,
                        "dia":15,
                        "hora":9,
                        "desc":"reunion importante"
                    },
                    {
                        "mes":6,
                        "dia":5,
                        "hora":15,
                        "desc":"Almuerzo con abuelo"
                    }
                ]
        }
    ]
}